apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts

resources:
- https://github.com/argoproj/rollouts-demo/examples/canary
- namespace.yaml
- gateway-httproute.yaml

patches:
  - target:
      kind: Ingress
    patch: |
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: DOES NOT MATTER