apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: alertmanager-http-redirect
  namespace: monitoring
spec:
  parentRefs:
  - group: gateway.networking.k8s.io	
    kind: Gateway
    name: cluster-north-south-gateway
    namespace: istio-gateway
    port: 80
  hostnames:
    - {{ .Values.alertmanager.url }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
      matches:	
        - path:	
            type: PathPrefix	
            value: /
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: alertmanager-https
  namespace: monitoring
spec:
  parentRefs:
  - group: gateway.networking.k8s.io	
    kind: Gateway
    name: cluster-north-south-gateway
    namespace: istio-gateway
    port: 443
  hostnames:
    - {{ .Values.alertmanager.url }}
  rules:
  - backendRefs:
     - group: ""
       kind: Service
       name: {{ .Values.alertmanager.service.name }}
       port: {{ .Values.alertmanager.service.port }}
       weight: 1
    matches:	
      - path:	
          type: PathPrefix	
          value: /