serviceAccount:
  name: cert-manager
volumeMounts:
  - name: token
    mountPath: "/var/run/service-account"
    readOnly: true
  - name: workload-identity-credential-configuration
    mountPath: "/etc/workload-identity"
    readOnly: true
extraEnv:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: "/etc/workload-identity/credential-configuration.json"
volumes:
  - name: token
    projected:
      sources:
      - serviceAccountToken:
          audience: "https://iam.googleapis.com/projects/463846382579/locations/global/workloadIdentityPools/custom-baremetal-pool/providers/argocd-cluster-provider"
          expirationSeconds: 3600
          path: token
  - name: workload-identity-credential-configuration
    configMap:
      name: certmanager-sa-wif