apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-api-crds
  namespace: argocd
spec:
  goTemplate: true
  # we default the destination to be itself...
  generators:
    # really only using this to match my .releaseName...
    # TODO: can this be combined with the helm values vs. 2 sources?
  - git:
      files:
      - path: clusters/*.yaml
      repoURL: "https://github.com/jimangel/cd.git"
      revision: HEAD
    selector:
      matchLabels:
        workloads.gateway-api-crds: "deployed"
  template:
    metadata:
      name: 'gateway-api-crds-{{ if eq .cluster.name "in-cluster" }}local{{ else }}{{ .cluster.friendlyName }}{{ end }}'
      labels:
        workloadType: networking
        environment: "{{ .themes.environment }}"
        # how is this workload deployed in argocd?
        syncType: "kustomize"
        # for quick ref
        cluster: "{{ .cluster.friendlyName }}"
      finalizers:
      - "resources-finalizer.argocd.argoproj.io"
    spec:
      project: default
      sources:
      - repoURL: https://github.com/jimangel/cd.git
        targetRevision: HEAD
        path: workloads/gateway-api-crds/config/overlays/{{ .themes.environment }}
      destination:
        name: '{{ .cluster.name }}'
        # no namespace, cluster wide CRDs...
        # namespace: ''
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true