apiVersion: v1
kind: Secret
metadata:
  name: gke-connect-gateway-service-account
  annotations:
    # We plan on overwriting with a "real" secret but this object allows the pods to mount / start
    # https://github.com/argoproj/argo-cd/issues/1373
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
stringData:
  # This is unused, see above.
  key.json: "PLACEHOLDER"