apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-api-istio-ingress
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      files:
      - path: clusters/*.yaml
      repoURL: "https://github.com/jimangel/cd.git"
      revision: HEAD
    selector:
      matchLabels:
        workloads.gateway-api-istio-ingress: "deployed"
  template:
    metadata:
      name: 'gateway-api-istio-ingress-{{ if eq .cluster.name "in-cluster" }}local{{ else }}{{ .cluster.friendlyName }}{{ end }}'
      labels:
        workloadType: networking
        environment: "{{ .themes.environment }}"
        provider: "{{ .themes.provider }}"
        # how is this workload deployed in argocd?
        syncType: "kustomize-nested-helm-remote"
        # for quick ref
        cluster: "{{ .cluster.friendlyName }}"
      finalizers:
      - "resources-finalizer.argocd.argoproj.io"
    spec:
      project: default
      sources:
      - repoURL: https://github.com/jimangel/cd.git
        path: workloads/gateway-api-istio-ingress/config/overlays/{{ .themes.provider }}
        targetRevision: HEAD
      destination:
        name: '{{ .cluster.name }}'
        # no namespace, cluster wide CRDs...
        namespace: 'istio-gateway'
      syncPolicy:
        automated: {}
        managedNamespaceMetadata:
          # kubectl label namespace default istio-injection=enabled
          labels:
            istio-injection: enabled
        syncOptions:
          - CreateNamespace=true