apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  goTemplate: true
  generators:
    # matrix 'parent' generator
  - matrix:
   #     # get the clusters to be impacted
      generators:
        # git generator, 'child' #1 == select clusters
        - git:
            files:
              - path: clusters/*.yaml
            repoURL: "https://github.com/jimangel/cd.git"
            revision: HEAD
            # only needed to avoid conflicts with the second generator
            pathParamPrefix: dest
          selector:
            matchLabels:
              workloads.kube-prometheus-stack: "deployed"
        - git:
            files:
              - path: workloads/kube-prometheus-stack/applicationset/environment/{{ .themes.environment }}.yaml
            repoURL: "https://github.com/jimangel/cd.git"
            revision: HEAD
  template:
    metadata:
      name: 'kube-prometheus-stack-{{ if eq .cluster.name "in-cluster" }}local{{ else }}{{ .cluster.friendlyName }}{{ end }}'
      labels:
        workloadType: sre
        environment: "{{ .themes.environment }}"
        # how is this workload deployed in argocd?
        syncType: "helm-remote-plus-helm-local"
        # for quick ref
        cluster: "{{ .cluster.friendlyName }}"
      finalizers:
      - "resources-finalizer.argocd.argoproj.io"
    spec:
      project: default
      sources:
      - chart: kube-prometheus-stack
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: '{{ .targetRevisionHelm }}'
        helm:
          values: |
            kubeProxy:
              enabled: false
            kubeEtcd:
              enabled: false
            prometheus:
              ingress:
                enabled: true
                ingressClassName: "nginx"
                hosts:
                  - prom.{{ if eq .cluster.domain "nip.io" }}{{ index .cluster "a-record" }}{{ else }}{{ .cluster.subdomain }}{{ end }}.{{ .cluster.domain }}
                tls:
                  - hosts:
                      - prom.{{ if eq .cluster.domain "nip.io" }}{{ index .cluster "a-record" }}{{ else }}{{ .cluster.subdomain }}{{ end }}.{{ .cluster.domain }}

            grafana:
              adminPassword: "H4Rd2Gu3szzs"
              ingress:
                enabled: true
                ingressClassName: "nginx"
                hosts:
                  - grafana.{{ if eq .cluster.domain "nip.io" }}{{ index .cluster "a-record" }}{{ else }}{{ .cluster.subdomain }}{{ end }}.{{ .cluster.domain }}
                tls:
                  - hosts:
                      - grafana.{{ if eq .cluster.domain "nip.io" }}{{ index .cluster "a-record" }}{{ else }}{{ .cluster.subdomain }}{{ end }}.{{ .cluster.domain }}

            alertmanager:
              ingress:
                enabled: true
                ingressClassName: "nginx"
                hosts:
                  - alertmanager.{{ if eq .cluster.domain "nip.io" }}{{ index .cluster "a-record" }}{{ else }}{{ .cluster.subdomain }}{{ end }}.{{ .cluster.domain }}
                tls:
                  - hosts:
                      - alertmanager.{{ if eq .cluster.domain "nip.io" }}{{ index .cluster "a-record" }}{{ else }}{{ .cluster.subdomain }}{{ end }}.{{ .cluster.domain }}
              alertmanagerSpec:
                externalUrl: https://alertmanager.{{ if eq .cluster.domain "nip.io" }}{{ index .cluster "a-record" }}{{ else }}{{ .cluster.subdomain }}{{ end }}.{{ .cluster.domain }}
          valueFiles:
          - $values/workloads/kube-prometheus-stack/config/helm-values/{{ .themes.environment }}.yaml
      - repoURL: "https://github.com/jimangel/cd.git"
        targetRevision: '{{ .targetRevisionGit }}'
        ref: values
      destination:
        name: '{{ .cluster.name }}'
        namespace: monitoring
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PruneLast=true