apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# You NEED >= 5.2.1 to support OCI repos
# https://github.com/kubernetes-sigs/kustomize/pull/5167

helmCharts:
- name: gateway-helm
  namespace: istio-system
  version: v0.0.0-latest
  repo: oci://docker.io/envoyproxy
#  valuesInline:
#    defaultRevision: "default"

