apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: applicationsetdefaultproject
spec:
  crd:
    spec:
      names:
        kind: ApplicationSetDefaultProject
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8svalid

        violation[{"msg": msg, "details": {}}] {
          input.review.object.kind == "ApplicationSet"
          not input.review.object.spec.project == "default"
          msg := sprintf("spec.project must be 'default' in %v", [input.review.object.metadata.name])
        }