namespace: istio-gateway

helmCharts:
- name: gateway
  version: 1.19.2
  repo: https://istio-release.storage.googleapis.com/charts
  releaseName: north-south-gateway

resources:
- ../../base
- gateway.yaml

patches:
- path: service-patch.yaml
  target:
    kind: Service
    name: north-south-gateway