apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-http-redirect
spec:
  parentRefs:
  - name: eg
    namespace: envoy-gateway-system
    port: 80
  hostnames:
    - argocd.gpu-local.cloudydemo.com
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-https-ui
spec:
  parentRefs:
  - name: eg
    namespace: envoy-gateway-system
    port: 443
  hostnames:
    - argocd.gpu-local.cloudydemo.com
  rules:
  -  backendRefs:
     - group: ""
       kind: Service
       name: argocd-server
       port: 80