apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      files:
      - path: clusters/*.yaml
      repoURL: "https://github.com/jimangel/cd.git"
      revision: HEAD
    selector:
      matchLabels:
        workloads.external-secrets-operator: "deployed"
  template:
    metadata:
      name: 'external-secrets-operator-{{ if eq .cluster.name "in-cluster" }}local{{ else }}{{ .cluster.friendlyName }}{{ end }}'
      labels:
        workloadType: security
        # document what selectors are used
        environment: "{{ .themes.environment }}"
        # how is this workload deployed in argocd?
        syncType: "helm-remote"
        # for quick ref
        cluster: "{{ .cluster.friendlyName }}"
      finalizers:
      - "resources-finalizer.argocd.argoproj.io"
    spec:
      project: default
      sources:
      - chart: external-secrets
        repoURL: https://charts.external-secrets.io
        targetRevision: '0.9.5'
        helm:
          #values: |
          #  arg1: val1
      destination:
        name: '{{ .cluster.name }}'
        # no namespace, cluster wide CRDs...
        namespace: 'external-secrets'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true