apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

commonAnnotations:
  # MUST MATCH THE APPSET NAME!!!
  app.kubernetes.io/instance: 01-self-managed-argo-local

resources:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.12.0
# add a RESTART YAML
- restart-argocd.yaml
- argocd-ingress.yaml

#components:
# extensions controller component
#- https://github.com/argoproj-labs/argocd-extensions/manifests

patches:
#- path: https://raw.githubusercontent.com/argoproj/argo-cd/master/notifications_catalog/install.yaml
#- path: argocd-notifications.yaml
- path: argocd-cmd-params-cm.yaml
# https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
- path: argocd-cm.yaml