apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: jupyter-notebook
  name: jupyter-notebook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-deployment-2
  namespace: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      runtimeClassName: nvidia
      containers:
      - name: jupyter-container-2
        #image: jupyter/scipy-notebook:python-3.10.10
        # cschranz/gpu-jupyter:v1.6_cuda-12.0_ubuntu-22.04
        # cschranz/gpu-jupyter:v1.5_cuda-11.8_ubuntu-22.04_python-only
        # cschranz/gpu-jupyter:v1.6_cuda-11.8_ubuntu-22.04
        # cschranz/gpu-jupyter:v1.6_cuda-12.0_ubuntu-22.04
        image: cschranz/gpu-jupyter:v1.6_cuda-12.0_ubuntu-22.04
        ports:
        - containerPort: 8888
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: JUPYTER_TOKEN
          value: "docker"
        - name: GRANT_SUDO
          value: "yes"
        - name: CHOWN_HOME
          value: "yes"
        - name: CHOWN_HOME_OPTS
          value: "-R"
        securityContext:
          runAsUser: 0 # This sets the user to root
        volumeMounts:
        - name: workdir
          mountPath: /home/jovyan/work
        - name: nfs-volume  # Mount the NFS volume here
          mountPath: /home/jovyan/work/nfs
        #  readOnly: true
        resources:
          limits:
            nvidia.com/gpu: 1
      nodeSelector:
        kubernetes.io/hostname: node2
      volumes:
      - name: workdir
        hostPath:
          path: /home/jangel/work # Adjust to your path
          type: DirectoryOrCreate
      - name: nfs-volume  # Define the NFS volume
        nfs:
          server: 172.16.4.100
          path: "/aiml"
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
  namespace: jupyter-notebook
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: jupyter-notebook
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: jupyter-http-redirect
  namespace: jupyter-notebook
spec:
  parentRefs:
  - name: eg
    namespace: envoy-gateway-system
    port: 80
  hostnames:
    - jupyter.gpu-local.cloudydemo.com
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: jupyter-https-ui
  namespace: jupyter-notebook
spec:
  parentRefs:
  - name: eg
    namespace: envoy-gateway-system
    port: 443
  hostnames:
    - jupyter.gpu-local.cloudydemo.com
  rules:
  -  backendRefs:
     - group: ""
       kind: Service
       name: jupyter-service
       port: 8888