apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argorollouts-canary-demo
  namespace: argocd
spec:
  goTemplate: true
  # we default the destination to be itself...
  generators:
    # really only using this to match my .releaseName...
    # TODO: can this be combined with the helm values vs. 2 sources?
  - git:
      files:
      - path: clusters/*.yaml
      repoURL: "https://github.com/jimangel/cd.git"
      revision: HEAD
    selector:
      matchLabels:
        workloads.argorollouts-canary-demo: "deployed"
  template:
    metadata:
      name: 'argorollouts-canary-demo-{{ if eq .cluster.name "in-cluster" }}local{{ else }}{{ .cluster.friendlyName }}{{ end }}'
      finalizers:
      - "resources-finalizer.argocd.argoproj.io"
      labels:
        workloadType: demo
        environment: "{{ .themes.environment }}"
        # how is this workload deployed in argocd?
        syncType: "kustomize-remote"
        # for quick ref
        cluster: "{{ .cluster.friendlyName }}"
    spec:
      project: default
      sources:
      - repoURL: https://github.com/jimangel/cd.git
        targetRevision: HEAD
        path: workloads/argorollouts-canary-demo/config/overlays/base
      destination:
        name: '{{ .cluster.name }}'
        namespace: 'argorollouts-demo'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true