name: Linting

on:
  pull_request:
    paths:
      - 'clusters/**.yaml'
      - 'scripts/lint_cluster_yaml.py'
      - 'Makefile'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linting
        run: make lint
